// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reply.proto

package loadbalancingbroker.protobuf;

public final class ReplyProto {
  private ReplyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 xBegin = 1;</code>
     */
    boolean hasXBegin();
    /**
     * <code>required int32 xBegin = 1;</code>
     */
    int getXBegin();

    /**
     * <code>required int32 xEnd = 2;</code>
     */
    boolean hasXEnd();
    /**
     * <code>required int32 xEnd = 2;</code>
     */
    int getXEnd();

    /**
     * <code>required int32 yBegin = 3;</code>
     */
    boolean hasYBegin();
    /**
     * <code>required int32 yBegin = 3;</code>
     */
    int getYBegin();

    /**
     * <code>required int32 yEnd = 4;</code>
     */
    boolean hasYEnd();
    /**
     * <code>required int32 yEnd = 4;</code>
     */
    int getYEnd();

    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    java.util.List<loadbalancingbroker.protobuf.ReplyProto.Reply.Row> 
        getRowsList();
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    loadbalancingbroker.protobuf.ReplyProto.Reply.Row getRows(int index);
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    java.util.List<? extends loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Reply}
   */
  public  static final class Reply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Reply)
      ReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reply() {
      rows_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              xBegin_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              xEnd_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              yBegin_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              yEnd_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                rows_ = new java.util.ArrayList<loadbalancingbroker.protobuf.ReplyProto.Reply.Row>();
                mutable_bitField0_ |= 0x00000010;
              }
              rows_.add(
                  input.readMessage(loadbalancingbroker.protobuf.ReplyProto.Reply.Row.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loadbalancingbroker.protobuf.ReplyProto.Reply.class, loadbalancingbroker.protobuf.ReplyProto.Reply.Builder.class);
    }

    public interface RowOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Reply.Row)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated int32 grayValues = 1;</code>
       */
      java.util.List<java.lang.Integer> getGrayValuesList();
      /**
       * <code>repeated int32 grayValues = 1;</code>
       */
      int getGrayValuesCount();
      /**
       * <code>repeated int32 grayValues = 1;</code>
       */
      int getGrayValues(int index);
    }
    /**
     * Protobuf type {@code Reply.Row}
     */
    public  static final class Row extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Reply.Row)
        RowOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Row.newBuilder() to construct.
      private Row(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Row() {
        grayValues_ = emptyIntList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Row(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  grayValues_ = newIntList();
                  mutable_bitField0_ |= 0x00000001;
                }
                grayValues_.addInt(input.readInt32());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                  grayValues_ = newIntList();
                  mutable_bitField0_ |= 0x00000001;
                }
                while (input.getBytesUntilLimit() > 0) {
                  grayValues_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            grayValues_.makeImmutable(); // C
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_Row_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loadbalancingbroker.protobuf.ReplyProto.Reply.Row.class, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder.class);
      }

      public static final int GRAYVALUES_FIELD_NUMBER = 1;
      private com.google.protobuf.Internal.IntList grayValues_;
      /**
       * <code>repeated int32 grayValues = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getGrayValuesList() {
        return grayValues_;
      }
      /**
       * <code>repeated int32 grayValues = 1;</code>
       */
      public int getGrayValuesCount() {
        return grayValues_.size();
      }
      /**
       * <code>repeated int32 grayValues = 1;</code>
       */
      public int getGrayValues(int index) {
        return grayValues_.getInt(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < grayValues_.size(); i++) {
          output.writeInt32(1, grayValues_.getInt(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < grayValues_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(grayValues_.getInt(i));
          }
          size += dataSize;
          size += 1 * getGrayValuesList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof loadbalancingbroker.protobuf.ReplyProto.Reply.Row)) {
          return super.equals(obj);
        }
        loadbalancingbroker.protobuf.ReplyProto.Reply.Row other = (loadbalancingbroker.protobuf.ReplyProto.Reply.Row) obj;

        if (!getGrayValuesList()
            .equals(other.getGrayValuesList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getGrayValuesCount() > 0) {
          hash = (37 * hash) + GRAYVALUES_FIELD_NUMBER;
          hash = (53 * hash) + getGrayValuesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(loadbalancingbroker.protobuf.ReplyProto.Reply.Row prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Reply.Row}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Reply.Row)
          loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_Row_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_Row_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  loadbalancingbroker.protobuf.ReplyProto.Reply.Row.class, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder.class);
        }

        // Construct using loadbalancingbroker.protobuf.ReplyProto.Reply.Row.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          grayValues_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_Row_descriptor;
        }

        @java.lang.Override
        public loadbalancingbroker.protobuf.ReplyProto.Reply.Row getDefaultInstanceForType() {
          return loadbalancingbroker.protobuf.ReplyProto.Reply.Row.getDefaultInstance();
        }

        @java.lang.Override
        public loadbalancingbroker.protobuf.ReplyProto.Reply.Row build() {
          loadbalancingbroker.protobuf.ReplyProto.Reply.Row result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public loadbalancingbroker.protobuf.ReplyProto.Reply.Row buildPartial() {
          loadbalancingbroker.protobuf.ReplyProto.Reply.Row result = new loadbalancingbroker.protobuf.ReplyProto.Reply.Row(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) != 0)) {
            grayValues_.makeImmutable();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.grayValues_ = grayValues_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof loadbalancingbroker.protobuf.ReplyProto.Reply.Row) {
            return mergeFrom((loadbalancingbroker.protobuf.ReplyProto.Reply.Row)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(loadbalancingbroker.protobuf.ReplyProto.Reply.Row other) {
          if (other == loadbalancingbroker.protobuf.ReplyProto.Reply.Row.getDefaultInstance()) return this;
          if (!other.grayValues_.isEmpty()) {
            if (grayValues_.isEmpty()) {
              grayValues_ = other.grayValues_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGrayValuesIsMutable();
              grayValues_.addAll(other.grayValues_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          loadbalancingbroker.protobuf.ReplyProto.Reply.Row parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (loadbalancingbroker.protobuf.ReplyProto.Reply.Row) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.Internal.IntList grayValues_ = emptyIntList();
        private void ensureGrayValuesIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            grayValues_ = mutableCopy(grayValues_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated int32 grayValues = 1;</code>
         */
        public java.util.List<java.lang.Integer>
            getGrayValuesList() {
          return ((bitField0_ & 0x00000001) != 0) ?
                   java.util.Collections.unmodifiableList(grayValues_) : grayValues_;
        }
        /**
         * <code>repeated int32 grayValues = 1;</code>
         */
        public int getGrayValuesCount() {
          return grayValues_.size();
        }
        /**
         * <code>repeated int32 grayValues = 1;</code>
         */
        public int getGrayValues(int index) {
          return grayValues_.getInt(index);
        }
        /**
         * <code>repeated int32 grayValues = 1;</code>
         */
        public Builder setGrayValues(
            int index, int value) {
          ensureGrayValuesIsMutable();
          grayValues_.setInt(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 grayValues = 1;</code>
         */
        public Builder addGrayValues(int value) {
          ensureGrayValuesIsMutable();
          grayValues_.addInt(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 grayValues = 1;</code>
         */
        public Builder addAllGrayValues(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureGrayValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, grayValues_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 grayValues = 1;</code>
         */
        public Builder clearGrayValues() {
          grayValues_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Reply.Row)
      }

      // @@protoc_insertion_point(class_scope:Reply.Row)
      private static final loadbalancingbroker.protobuf.ReplyProto.Reply.Row DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new loadbalancingbroker.protobuf.ReplyProto.Reply.Row();
      }

      public static loadbalancingbroker.protobuf.ReplyProto.Reply.Row getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Row>
          PARSER = new com.google.protobuf.AbstractParser<Row>() {
        @java.lang.Override
        public Row parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Row(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Row> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Row> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public loadbalancingbroker.protobuf.ReplyProto.Reply.Row getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int XBEGIN_FIELD_NUMBER = 1;
    private int xBegin_;
    /**
     * <code>required int32 xBegin = 1;</code>
     */
    public boolean hasXBegin() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 xBegin = 1;</code>
     */
    public int getXBegin() {
      return xBegin_;
    }

    public static final int XEND_FIELD_NUMBER = 2;
    private int xEnd_;
    /**
     * <code>required int32 xEnd = 2;</code>
     */
    public boolean hasXEnd() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 xEnd = 2;</code>
     */
    public int getXEnd() {
      return xEnd_;
    }

    public static final int YBEGIN_FIELD_NUMBER = 3;
    private int yBegin_;
    /**
     * <code>required int32 yBegin = 3;</code>
     */
    public boolean hasYBegin() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 yBegin = 3;</code>
     */
    public int getYBegin() {
      return yBegin_;
    }

    public static final int YEND_FIELD_NUMBER = 4;
    private int yEnd_;
    /**
     * <code>required int32 yEnd = 4;</code>
     */
    public boolean hasYEnd() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 yEnd = 4;</code>
     */
    public int getYEnd() {
      return yEnd_;
    }

    public static final int ROWS_FIELD_NUMBER = 5;
    private java.util.List<loadbalancingbroker.protobuf.ReplyProto.Reply.Row> rows_;
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    public java.util.List<loadbalancingbroker.protobuf.ReplyProto.Reply.Row> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    public java.util.List<? extends loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    public loadbalancingbroker.protobuf.ReplyProto.Reply.Row getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .Reply.Row rows = 5;</code>
     */
    public loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasXBegin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasXEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYBegin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, xBegin_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, xEnd_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, yBegin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, yEnd_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(5, rows_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, xBegin_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, xEnd_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, yBegin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, yEnd_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, rows_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof loadbalancingbroker.protobuf.ReplyProto.Reply)) {
        return super.equals(obj);
      }
      loadbalancingbroker.protobuf.ReplyProto.Reply other = (loadbalancingbroker.protobuf.ReplyProto.Reply) obj;

      if (hasXBegin() != other.hasXBegin()) return false;
      if (hasXBegin()) {
        if (getXBegin()
            != other.getXBegin()) return false;
      }
      if (hasXEnd() != other.hasXEnd()) return false;
      if (hasXEnd()) {
        if (getXEnd()
            != other.getXEnd()) return false;
      }
      if (hasYBegin() != other.hasYBegin()) return false;
      if (hasYBegin()) {
        if (getYBegin()
            != other.getYBegin()) return false;
      }
      if (hasYEnd() != other.hasYEnd()) return false;
      if (hasYEnd()) {
        if (getYEnd()
            != other.getYEnd()) return false;
      }
      if (!getRowsList()
          .equals(other.getRowsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasXBegin()) {
        hash = (37 * hash) + XBEGIN_FIELD_NUMBER;
        hash = (53 * hash) + getXBegin();
      }
      if (hasXEnd()) {
        hash = (37 * hash) + XEND_FIELD_NUMBER;
        hash = (53 * hash) + getXEnd();
      }
      if (hasYBegin()) {
        hash = (37 * hash) + YBEGIN_FIELD_NUMBER;
        hash = (53 * hash) + getYBegin();
      }
      if (hasYEnd()) {
        hash = (37 * hash) + YEND_FIELD_NUMBER;
        hash = (53 * hash) + getYEnd();
      }
      if (getRowsCount() > 0) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRowsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static loadbalancingbroker.protobuf.ReplyProto.Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(loadbalancingbroker.protobuf.ReplyProto.Reply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Reply)
        loadbalancingbroker.protobuf.ReplyProto.ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loadbalancingbroker.protobuf.ReplyProto.Reply.class, loadbalancingbroker.protobuf.ReplyProto.Reply.Builder.class);
      }

      // Construct using loadbalancingbroker.protobuf.ReplyProto.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        xBegin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        xEnd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        yBegin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        yEnd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return loadbalancingbroker.protobuf.ReplyProto.internal_static_Reply_descriptor;
      }

      @java.lang.Override
      public loadbalancingbroker.protobuf.ReplyProto.Reply getDefaultInstanceForType() {
        return loadbalancingbroker.protobuf.ReplyProto.Reply.getDefaultInstance();
      }

      @java.lang.Override
      public loadbalancingbroker.protobuf.ReplyProto.Reply build() {
        loadbalancingbroker.protobuf.ReplyProto.Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public loadbalancingbroker.protobuf.ReplyProto.Reply buildPartial() {
        loadbalancingbroker.protobuf.ReplyProto.Reply result = new loadbalancingbroker.protobuf.ReplyProto.Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.xBegin_ = xBegin_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.xEnd_ = xEnd_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.yBegin_ = yBegin_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.yEnd_ = yEnd_;
          to_bitField0_ |= 0x00000008;
        }
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof loadbalancingbroker.protobuf.ReplyProto.Reply) {
          return mergeFrom((loadbalancingbroker.protobuf.ReplyProto.Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(loadbalancingbroker.protobuf.ReplyProto.Reply other) {
        if (other == loadbalancingbroker.protobuf.ReplyProto.Reply.getDefaultInstance()) return this;
        if (other.hasXBegin()) {
          setXBegin(other.getXBegin());
        }
        if (other.hasXEnd()) {
          setXEnd(other.getXEnd());
        }
        if (other.hasYBegin()) {
          setYBegin(other.getYBegin());
        }
        if (other.hasYEnd()) {
          setYEnd(other.getYEnd());
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000010);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasXBegin()) {
          return false;
        }
        if (!hasXEnd()) {
          return false;
        }
        if (!hasYBegin()) {
          return false;
        }
        if (!hasYEnd()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        loadbalancingbroker.protobuf.ReplyProto.Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (loadbalancingbroker.protobuf.ReplyProto.Reply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int xBegin_ ;
      /**
       * <code>required int32 xBegin = 1;</code>
       */
      public boolean hasXBegin() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 xBegin = 1;</code>
       */
      public int getXBegin() {
        return xBegin_;
      }
      /**
       * <code>required int32 xBegin = 1;</code>
       */
      public Builder setXBegin(int value) {
        bitField0_ |= 0x00000001;
        xBegin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xBegin = 1;</code>
       */
      public Builder clearXBegin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        xBegin_ = 0;
        onChanged();
        return this;
      }

      private int xEnd_ ;
      /**
       * <code>required int32 xEnd = 2;</code>
       */
      public boolean hasXEnd() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 xEnd = 2;</code>
       */
      public int getXEnd() {
        return xEnd_;
      }
      /**
       * <code>required int32 xEnd = 2;</code>
       */
      public Builder setXEnd(int value) {
        bitField0_ |= 0x00000002;
        xEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xEnd = 2;</code>
       */
      public Builder clearXEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        xEnd_ = 0;
        onChanged();
        return this;
      }

      private int yBegin_ ;
      /**
       * <code>required int32 yBegin = 3;</code>
       */
      public boolean hasYBegin() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 yBegin = 3;</code>
       */
      public int getYBegin() {
        return yBegin_;
      }
      /**
       * <code>required int32 yBegin = 3;</code>
       */
      public Builder setYBegin(int value) {
        bitField0_ |= 0x00000004;
        yBegin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 yBegin = 3;</code>
       */
      public Builder clearYBegin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        yBegin_ = 0;
        onChanged();
        return this;
      }

      private int yEnd_ ;
      /**
       * <code>required int32 yEnd = 4;</code>
       */
      public boolean hasYEnd() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 yEnd = 4;</code>
       */
      public int getYEnd() {
        return yEnd_;
      }
      /**
       * <code>required int32 yEnd = 4;</code>
       */
      public Builder setYEnd(int value) {
        bitField0_ |= 0x00000008;
        yEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 yEnd = 4;</code>
       */
      public Builder clearYEnd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        yEnd_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<loadbalancingbroker.protobuf.ReplyProto.Reply.Row> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          rows_ = new java.util.ArrayList<loadbalancingbroker.protobuf.ReplyProto.Reply.Row>(rows_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          loadbalancingbroker.protobuf.ReplyProto.Reply.Row, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder, loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public java.util.List<loadbalancingbroker.protobuf.ReplyProto.Reply.Row> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public loadbalancingbroker.protobuf.ReplyProto.Reply.Row getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder setRows(
          int index, loadbalancingbroker.protobuf.ReplyProto.Reply.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder setRows(
          int index, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder addRows(loadbalancingbroker.protobuf.ReplyProto.Reply.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder addRows(
          int index, loadbalancingbroker.protobuf.ReplyProto.Reply.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder addRows(
          loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder addRows(
          int index, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends loadbalancingbroker.protobuf.ReplyProto.Reply.Row> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public java.util.List<? extends loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            loadbalancingbroker.protobuf.ReplyProto.Reply.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .Reply.Row rows = 5;</code>
       */
      public java.util.List<loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          loadbalancingbroker.protobuf.ReplyProto.Reply.Row, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder, loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              loadbalancingbroker.protobuf.ReplyProto.Reply.Row, loadbalancingbroker.protobuf.ReplyProto.Reply.Row.Builder, loadbalancingbroker.protobuf.ReplyProto.Reply.RowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Reply)
    }

    // @@protoc_insertion_point(class_scope:Reply)
    private static final loadbalancingbroker.protobuf.ReplyProto.Reply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new loadbalancingbroker.protobuf.ReplyProto.Reply();
    }

    public static loadbalancingbroker.protobuf.ReplyProto.Reply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Reply>
        PARSER = new com.google.protobuf.AbstractParser<Reply>() {
      @java.lang.Override
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public loadbalancingbroker.protobuf.ReplyProto.Reply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reply_Row_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reply_Row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Reply.proto\"x\n\005Reply\022\016\n\006xBegin\030\001 \002(\005\022\014" +
      "\n\004xEnd\030\002 \002(\005\022\016\n\006yBegin\030\003 \002(\005\022\014\n\004yEnd\030\004 \002" +
      "(\005\022\030\n\004rows\030\005 \003(\0132\n.Reply.Row\032\031\n\003Row\022\022\n\ng" +
      "rayValues\030\001 \003(\005B*\n\034loadbalancingbroker.p" +
      "rotobufB\nReplyProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Reply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reply_descriptor,
        new java.lang.String[] { "XBegin", "XEnd", "YBegin", "YEnd", "Rows", });
    internal_static_Reply_Row_descriptor =
      internal_static_Reply_descriptor.getNestedTypes().get(0);
    internal_static_Reply_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reply_Row_descriptor,
        new java.lang.String[] { "GrayValues", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
