// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package loadbalancingbroker.protobuf;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 imgWidth = 1;</code>
     */
    boolean hasImgWidth();
    /**
     * <code>required int32 imgWidth = 1;</code>
     */
    int getImgWidth();

    /**
     * <code>required int32 imgHeight = 2;</code>
     */
    boolean hasImgHeight();
    /**
     * <code>required int32 imgHeight = 2;</code>
     */
    int getImgHeight();

    /**
     * <code>required int32 xBegin = 3;</code>
     */
    boolean hasXBegin();
    /**
     * <code>required int32 xBegin = 3;</code>
     */
    int getXBegin();

    /**
     * <code>required int32 xEnd = 4;</code>
     */
    boolean hasXEnd();
    /**
     * <code>required int32 xEnd = 4;</code>
     */
    int getXEnd();

    /**
     * <code>required int32 yBegin = 5;</code>
     */
    boolean hasYBegin();
    /**
     * <code>required int32 yBegin = 5;</code>
     */
    int getYBegin();

    /**
     * <code>required int32 yEnd = 6;</code>
     */
    boolean hasYEnd();
    /**
     * <code>required int32 yEnd = 6;</code>
     */
    int getYEnd();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              imgWidth_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              imgHeight_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              xBegin_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              xEnd_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              yBegin_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              yEnd_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loadbalancingbroker.protobuf.RequestProto.internal_static_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loadbalancingbroker.protobuf.RequestProto.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loadbalancingbroker.protobuf.RequestProto.Request.class, loadbalancingbroker.protobuf.RequestProto.Request.Builder.class);
    }

    private int bitField0_;
    public static final int IMGWIDTH_FIELD_NUMBER = 1;
    private int imgWidth_;
    /**
     * <code>required int32 imgWidth = 1;</code>
     */
    public boolean hasImgWidth() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 imgWidth = 1;</code>
     */
    public int getImgWidth() {
      return imgWidth_;
    }

    public static final int IMGHEIGHT_FIELD_NUMBER = 2;
    private int imgHeight_;
    /**
     * <code>required int32 imgHeight = 2;</code>
     */
    public boolean hasImgHeight() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 imgHeight = 2;</code>
     */
    public int getImgHeight() {
      return imgHeight_;
    }

    public static final int XBEGIN_FIELD_NUMBER = 3;
    private int xBegin_;
    /**
     * <code>required int32 xBegin = 3;</code>
     */
    public boolean hasXBegin() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 xBegin = 3;</code>
     */
    public int getXBegin() {
      return xBegin_;
    }

    public static final int XEND_FIELD_NUMBER = 4;
    private int xEnd_;
    /**
     * <code>required int32 xEnd = 4;</code>
     */
    public boolean hasXEnd() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 xEnd = 4;</code>
     */
    public int getXEnd() {
      return xEnd_;
    }

    public static final int YBEGIN_FIELD_NUMBER = 5;
    private int yBegin_;
    /**
     * <code>required int32 yBegin = 5;</code>
     */
    public boolean hasYBegin() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 yBegin = 5;</code>
     */
    public int getYBegin() {
      return yBegin_;
    }

    public static final int YEND_FIELD_NUMBER = 6;
    private int yEnd_;
    /**
     * <code>required int32 yEnd = 6;</code>
     */
    public boolean hasYEnd() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 yEnd = 6;</code>
     */
    public int getYEnd() {
      return yEnd_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasImgWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImgHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasXBegin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasXEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYBegin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, imgWidth_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, imgHeight_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, xBegin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, xEnd_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, yBegin_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, yEnd_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, imgWidth_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, imgHeight_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, xBegin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, xEnd_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, yBegin_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, yEnd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof loadbalancingbroker.protobuf.RequestProto.Request)) {
        return super.equals(obj);
      }
      loadbalancingbroker.protobuf.RequestProto.Request other = (loadbalancingbroker.protobuf.RequestProto.Request) obj;

      if (hasImgWidth() != other.hasImgWidth()) return false;
      if (hasImgWidth()) {
        if (getImgWidth()
            != other.getImgWidth()) return false;
      }
      if (hasImgHeight() != other.hasImgHeight()) return false;
      if (hasImgHeight()) {
        if (getImgHeight()
            != other.getImgHeight()) return false;
      }
      if (hasXBegin() != other.hasXBegin()) return false;
      if (hasXBegin()) {
        if (getXBegin()
            != other.getXBegin()) return false;
      }
      if (hasXEnd() != other.hasXEnd()) return false;
      if (hasXEnd()) {
        if (getXEnd()
            != other.getXEnd()) return false;
      }
      if (hasYBegin() != other.hasYBegin()) return false;
      if (hasYBegin()) {
        if (getYBegin()
            != other.getYBegin()) return false;
      }
      if (hasYEnd() != other.hasYEnd()) return false;
      if (hasYEnd()) {
        if (getYEnd()
            != other.getYEnd()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasImgWidth()) {
        hash = (37 * hash) + IMGWIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getImgWidth();
      }
      if (hasImgHeight()) {
        hash = (37 * hash) + IMGHEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getImgHeight();
      }
      if (hasXBegin()) {
        hash = (37 * hash) + XBEGIN_FIELD_NUMBER;
        hash = (53 * hash) + getXBegin();
      }
      if (hasXEnd()) {
        hash = (37 * hash) + XEND_FIELD_NUMBER;
        hash = (53 * hash) + getXEnd();
      }
      if (hasYBegin()) {
        hash = (37 * hash) + YBEGIN_FIELD_NUMBER;
        hash = (53 * hash) + getYBegin();
      }
      if (hasYEnd()) {
        hash = (37 * hash) + YEND_FIELD_NUMBER;
        hash = (53 * hash) + getYEnd();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static loadbalancingbroker.protobuf.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(loadbalancingbroker.protobuf.RequestProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        loadbalancingbroker.protobuf.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return loadbalancingbroker.protobuf.RequestProto.internal_static_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return loadbalancingbroker.protobuf.RequestProto.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                loadbalancingbroker.protobuf.RequestProto.Request.class, loadbalancingbroker.protobuf.RequestProto.Request.Builder.class);
      }

      // Construct using loadbalancingbroker.protobuf.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        imgWidth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        imgHeight_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        xBegin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        xEnd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        yBegin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        yEnd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return loadbalancingbroker.protobuf.RequestProto.internal_static_Request_descriptor;
      }

      @java.lang.Override
      public loadbalancingbroker.protobuf.RequestProto.Request getDefaultInstanceForType() {
        return loadbalancingbroker.protobuf.RequestProto.Request.getDefaultInstance();
      }

      @java.lang.Override
      public loadbalancingbroker.protobuf.RequestProto.Request build() {
        loadbalancingbroker.protobuf.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public loadbalancingbroker.protobuf.RequestProto.Request buildPartial() {
        loadbalancingbroker.protobuf.RequestProto.Request result = new loadbalancingbroker.protobuf.RequestProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.imgWidth_ = imgWidth_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.imgHeight_ = imgHeight_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.xBegin_ = xBegin_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.xEnd_ = xEnd_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.yBegin_ = yBegin_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.yEnd_ = yEnd_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof loadbalancingbroker.protobuf.RequestProto.Request) {
          return mergeFrom((loadbalancingbroker.protobuf.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(loadbalancingbroker.protobuf.RequestProto.Request other) {
        if (other == loadbalancingbroker.protobuf.RequestProto.Request.getDefaultInstance()) return this;
        if (other.hasImgWidth()) {
          setImgWidth(other.getImgWidth());
        }
        if (other.hasImgHeight()) {
          setImgHeight(other.getImgHeight());
        }
        if (other.hasXBegin()) {
          setXBegin(other.getXBegin());
        }
        if (other.hasXEnd()) {
          setXEnd(other.getXEnd());
        }
        if (other.hasYBegin()) {
          setYBegin(other.getYBegin());
        }
        if (other.hasYEnd()) {
          setYEnd(other.getYEnd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasImgWidth()) {
          return false;
        }
        if (!hasImgHeight()) {
          return false;
        }
        if (!hasXBegin()) {
          return false;
        }
        if (!hasXEnd()) {
          return false;
        }
        if (!hasYBegin()) {
          return false;
        }
        if (!hasYEnd()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        loadbalancingbroker.protobuf.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (loadbalancingbroker.protobuf.RequestProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int imgWidth_ ;
      /**
       * <code>required int32 imgWidth = 1;</code>
       */
      public boolean hasImgWidth() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 imgWidth = 1;</code>
       */
      public int getImgWidth() {
        return imgWidth_;
      }
      /**
       * <code>required int32 imgWidth = 1;</code>
       */
      public Builder setImgWidth(int value) {
        bitField0_ |= 0x00000001;
        imgWidth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 imgWidth = 1;</code>
       */
      public Builder clearImgWidth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imgWidth_ = 0;
        onChanged();
        return this;
      }

      private int imgHeight_ ;
      /**
       * <code>required int32 imgHeight = 2;</code>
       */
      public boolean hasImgHeight() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 imgHeight = 2;</code>
       */
      public int getImgHeight() {
        return imgHeight_;
      }
      /**
       * <code>required int32 imgHeight = 2;</code>
       */
      public Builder setImgHeight(int value) {
        bitField0_ |= 0x00000002;
        imgHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 imgHeight = 2;</code>
       */
      public Builder clearImgHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        imgHeight_ = 0;
        onChanged();
        return this;
      }

      private int xBegin_ ;
      /**
       * <code>required int32 xBegin = 3;</code>
       */
      public boolean hasXBegin() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 xBegin = 3;</code>
       */
      public int getXBegin() {
        return xBegin_;
      }
      /**
       * <code>required int32 xBegin = 3;</code>
       */
      public Builder setXBegin(int value) {
        bitField0_ |= 0x00000004;
        xBegin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xBegin = 3;</code>
       */
      public Builder clearXBegin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        xBegin_ = 0;
        onChanged();
        return this;
      }

      private int xEnd_ ;
      /**
       * <code>required int32 xEnd = 4;</code>
       */
      public boolean hasXEnd() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 xEnd = 4;</code>
       */
      public int getXEnd() {
        return xEnd_;
      }
      /**
       * <code>required int32 xEnd = 4;</code>
       */
      public Builder setXEnd(int value) {
        bitField0_ |= 0x00000008;
        xEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 xEnd = 4;</code>
       */
      public Builder clearXEnd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        xEnd_ = 0;
        onChanged();
        return this;
      }

      private int yBegin_ ;
      /**
       * <code>required int32 yBegin = 5;</code>
       */
      public boolean hasYBegin() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 yBegin = 5;</code>
       */
      public int getYBegin() {
        return yBegin_;
      }
      /**
       * <code>required int32 yBegin = 5;</code>
       */
      public Builder setYBegin(int value) {
        bitField0_ |= 0x00000010;
        yBegin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 yBegin = 5;</code>
       */
      public Builder clearYBegin() {
        bitField0_ = (bitField0_ & ~0x00000010);
        yBegin_ = 0;
        onChanged();
        return this;
      }

      private int yEnd_ ;
      /**
       * <code>required int32 yEnd = 6;</code>
       */
      public boolean hasYEnd() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int32 yEnd = 6;</code>
       */
      public int getYEnd() {
        return yEnd_;
      }
      /**
       * <code>required int32 yEnd = 6;</code>
       */
      public Builder setYEnd(int value) {
        bitField0_ |= 0x00000020;
        yEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 yEnd = 6;</code>
       */
      public Builder clearYEnd() {
        bitField0_ = (bitField0_ & ~0x00000020);
        yEnd_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final loadbalancingbroker.protobuf.RequestProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new loadbalancingbroker.protobuf.RequestProto.Request();
    }

    public static loadbalancingbroker.protobuf.RequestProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public loadbalancingbroker.protobuf.RequestProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\"j\n\007Request\022\020\n\010imgWidth\030\001" +
      " \002(\005\022\021\n\timgHeight\030\002 \002(\005\022\016\n\006xBegin\030\003 \002(\005\022" +
      "\014\n\004xEnd\030\004 \002(\005\022\016\n\006yBegin\030\005 \002(\005\022\014\n\004yEnd\030\006 " +
      "\002(\005B,\n\034loadbalancingbroker.protobufB\014Req" +
      "uestProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "ImgWidth", "ImgHeight", "XBegin", "XEnd", "YBegin", "YEnd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
